name: CI

on:
- push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-16.04
        - macos-latest
        - windows-latest
        ruby_version:
        - 2.7
        - 2.6
        - 2.5
        - 2.4

    steps:
    - name: Setup Ruby
      if: matrix.ruby_version != 'master-nightly'
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: ${{ matrix.ruby_version }}

    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Prepare environment
      run: |
        gem install bundler

    - name: Install requirements
      run: |
        bundle install --jobs 4 --retry 3

    - name: Test
      run: |
        bundle exec rake
